#define DIODE_DIRECTION COL2ROW
#define MATRIX_ROWS 4
#define MATRIX_COLS 6

#define EE_HANDS
#define SPLIT_USB_DETECT
#define USE_SERIAL

// #define SOFT_SERIAL_PIN GP13
// #define SERIAL_PIO_USE_PIO1

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP12
#define SERIAL_USART_RX_PIN GP13
#define SERIAL_USART_PIN_SWAP

#define MATRIX_ROW_PINS { GP12, GP11, GP10, GP9 }
#define MATRIX_COL_PINS { GP28, GP29, GP26, GP27, G14, G15}

// #define ENCODERS_PAD_A { GP8 }
// #define ENCODERS_PAD_B { GP7 }

// #define MATRIX_ROW_PINS_RIGHT { GP0, GP1, GP8, GP14 }
// #define MATRIX_COL_PINS_RIGHT { GP7, GP6, GP5, GP4, GP3, GP29 }

// #define ENCODERS_PAD_A_RIGHT { GP15 }
// #define ENCODERS_PAD_B_RIGHT { GP26 }

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define TAPPING_TERM 190
// #define IGNORE_MOD_TAP_INTERRUPT
#define I2C_DRIVER	I2CD1
// #define I2C1_SDA_PIN  GP2
// #define I2C1_SCL_PIN  GP3

#define OLED_IC  OLED_IC_SH1106
#define OLED_COLUMN_OFFSET