// #define DIODE_DIRECTION COL2ROW
// #define MATRIX_ROWS 8
// #define MATRIX_COLS 6

// #define MASTER_LEFT
// #define SPLIT_HAND_PIN GP1

// #define USE_SERIAL
// #define SOFT_SERIAL_PIN GP0

// #define MATRIX_ROW_PINS { GP4, GP5, GP6, GP7 }
// #define MATRIX_COL_PINS { GP8, GP9, GP10, GP11, GP12, GP13}

// #define MATRIX_ROW_PINS_RIGHT { GP28, GP27, GP26, GP15 }
// #define MATRIX_COL_PINS_RIGHT { GP9, GP10, GP11, GP12, GP13, GP14}

// #define ENCODERS_PAD_A { GP7 }
// #define ENCODERS_PAD_B { GP8 }

// #define ENCODERS_PAD_A_RIGHT { GP7 }
// #define ENCODERS_PAD_B_RIGHT { GP8 }

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

// #define BOOTMAGIC_ROW_RIGHT 4
// #define BOOTMAGIC_COLUMN_RIGHT 5

// #define BOOTMAGIC_ROW 0
// #define BOOTMAGIC_COLUMN 0

#define I2C_DRIVER	I2CD1
#define OLED_IC  OLED_IC_SH1106
#define OLED_COLUMN_OFFSET 2