MCU = RP2040
# BOOTLOADER = rp2040

# SPLIT_KEYBOARD = yes
# SERIAL_DRIVER = vendor

# ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
# EXTRAKEY_ENABLE = yes
# CAPS_WORD_ENABLE = yes

# CONSOLE_ENABLE = yes

# OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c