MCU = RP2040
# BOOTLOADER = rp2040

# SPLIT_KEYBOARD = yes
# SERIAL_DRIVER = vendor

# ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes

BACKLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = yes
LTO_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c